// constants.js
export const CATEGORY_OPTIONS = [
    "Electronics",
    "Accessories",
    "Personal Items",
    "Apparel",
    "Documents",
    "Stationery",
    "Food Containers",
    "Drink Containers",
    "Bag",
    "Health Products",
    "Hygiene Products",
    "Sports",
    "Watch",
    "Tool",        
    "Headphone",
    "Earphone",
    "Phone",
    "Bottle",
    "Book",
    "Vallet",
    "Camera",
    "Key",
    "Jacket",
    "Coat",
    "Blazor",
    "Jerkin",
    "Others"
    
];
